spring.config.activate.on-profile=dev
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.jpa.properties.hibernate.default_schema=public
